# Generated by Django 2.2.15 on 2020-08-31 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homemidelname', '0001_initial'),
        ('hwahawwaiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='udobshiyttah',
            name='jhfghjgjhgjhgjhg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='udobshiyttah_jhfghjgjhgjhgjhg', to='homemidelname.Huskywhitecolour'),
        ),
    ]
